import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faUser,
    faShoppingCart,
    faSearch,
    faHeart,
    faStar,
    faTrash,
    faPlus,
    faMinus,
    faTimes,
    faBars,
    faPhone,
    faEnvelope,
    faMapMarkerAlt,
    faTruck,
    faTruckFast,
    faCreditCard,
    faCheck,
    faChevronDown,
    faChevronRight,
    faChevronLeft,
    faGift,
    faTag,
    faPercent,
    faArrowRight,
    faHome,
    faQrcode,
    faBuildingColumns,
} from '@fortawesome/free-solid-svg-icons';

import {
    faFacebookF,
    faInstagram,
    faYoutube,
    faTiktok, faGoogle,
} from '@fortawesome/free-brands-svg-icons';

library.add(
    faUser,
    faShoppingCart,
    faSearch,
    faHeart,
    faStar,
    faTrash,
    faPlus,
    faMinus,
    faTimes,
    faBars,
    faPhone,
    faEnvelope,
    faMapMarkerAlt,
    faTruck,
    faTruckFast,
    faQrcode,
    faCreditCard,
    faCheck,
    faChevronDown,
    faChevronRight,
    faChevronLeft,
    faGift,
    faTag,
    faPercent,
    faArrowRight,
    faHome,
    faFacebookF,
    faInstagram,
    faYoutube,
    faTiktok,
    faGoogle,
    faBuildingColumns,
);

export default FontAwesomeIcon;